"""initial schema — all 11 tables from Base.metadata

Revision ID: 498638f987ec
Revises: 
Create Date: 2026-05-26 04:16:55.968290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base  # for JSONBOrJSON custom type referenced below


# revision identifiers, used by Alembic.
revision: str = '498638f987ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor_id', sa.String(length=80), nullable=False),
    sa.Column('actor_role', sa.String(length=40), nullable=False),
    sa.Column('actor_facility_id', sa.String(length=26), nullable=True),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('purpose', sa.String(length=300), nullable=True),
    sa.Column('consent_id', sa.String(length=26), nullable=True),
    sa.Column('extra', app.db.base.JSONBOrJSON(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_facility_id'), 'audit_log', ['actor_facility_id'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_role'), 'audit_log', ['actor_role'], unique=False)
    op.create_index('ix_audit_log_actor_time', 'audit_log', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_log_resource', 'audit_log', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_id'), 'audit_log', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_type'), 'audit_log', ['resource_type'], unique=False)
    op.create_table('facilities',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('level', sa.String(length=40), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('sub_county', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities'))
    )
    op.create_index(op.f('ix_facilities_code'), 'facilities', ['code'], unique=True)
    op.create_index(op.f('ix_facilities_district'), 'facilities', ['district'], unique=False)
    op.create_index(op.f('ix_facilities_level'), 'facilities', ['level'], unique=False)
    op.create_index(op.f('ix_facilities_name'), 'facilities', ['name'], unique=False)
    op.create_table('patients',
    sa.Column('nin', sa.String(length=14), nullable=False),
    sa.Column('given_name', sa.String(length=80), nullable=False),
    sa.Column('family_name', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('sub_county', sa.String(length=80), nullable=True),
    sa.Column('parish', sa.String(length=80), nullable=True),
    sa.Column('village', sa.String(length=80), nullable=True),
    sa.Column('deceased', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('record_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    op.create_index(op.f('ix_patients_district'), 'patients', ['district'], unique=False)
    op.create_index('ix_patients_family_name_trgm', 'patients', ['family_name'], unique=False, postgresql_using='gin', postgresql_ops={'family_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_patients_nin'), 'patients', ['nin'], unique=True)
    op.create_table('supply_items',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('reorder_threshold', sa.Integer(), nullable=False),
    sa.Column('requires_cold_chain', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supply_items'))
    )
    op.create_index(op.f('ix_supply_items_category'), 'supply_items', ['category'], unique=False)
    op.create_index(op.f('ix_supply_items_code'), 'supply_items', ['code'], unique=True)
    op.create_index(op.f('ix_supply_items_name'), 'supply_items', ['name'], unique=False)
    op.create_table('consents',
    sa.Column('patient_id', sa.String(length=26), nullable=False),
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=300), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_consents_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    op.create_index(op.f('ix_consents_patient_id'), 'consents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_consents_scope'), 'consents', ['scope'], unique=False)
    op.create_table('encounters',
    sa.Column('patient_id', sa.String(length=26), nullable=False),
    sa.Column('facility_id', sa.String(length=26), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('diagnosis_codes', app.db.base.JSONBOrJSON(), nullable=False),
    sa.Column('recorded_by', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_encounters_facility_id_facilities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_encounters_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounters'))
    )
    op.create_index(op.f('ix_encounters_facility_id'), 'encounters', ['facility_id'], unique=False)
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_index(op.f('ix_encounters_started_at'), 'encounters', ['started_at'], unique=False)
    op.create_table('stock_batches',
    sa.Column('supply_item_id', sa.String(length=26), nullable=False),
    sa.Column('facility_id', sa.String(length=26), nullable=False),
    sa.Column('lot_number', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('cost_ugx', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_stock_batches_facility_id_facilities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supply_item_id'], ['supply_items.id'], name=op.f('fk_stock_batches_supply_item_id_supply_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_batches'))
    )
    op.create_index(op.f('ix_stock_batches_expires_on'), 'stock_batches', ['expires_on'], unique=False)
    op.create_index(op.f('ix_stock_batches_facility_id'), 'stock_batches', ['facility_id'], unique=False)
    op.create_index('ix_stock_batches_facility_item', 'stock_batches', ['facility_id', 'supply_item_id'], unique=False)
    op.create_index(op.f('ix_stock_batches_lot_number'), 'stock_batches', ['lot_number'], unique=False)
    op.create_index(op.f('ix_stock_batches_supply_item_id'), 'stock_batches', ['supply_item_id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('from_facility_id', sa.String(length=26), nullable=False),
    sa.Column('to_facility_id', sa.String(length=26), nullable=False),
    sa.Column('supply_item_id', sa.String(length=26), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('initiated_by', sa.String(length=80), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_facility_id'], ['facilities.id'], name=op.f('fk_stock_transfers_from_facility_id_facilities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supply_item_id'], ['supply_items.id'], name=op.f('fk_stock_transfers_supply_item_id_supply_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_facility_id'], ['facilities.id'], name=op.f('fk_stock_transfers_to_facility_id_facilities'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_transfers'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('facility_id', sa.String(length=26), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_users_facility_id_facilities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index(op.f('ix_users_facility_id'), 'users', ['facility_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('observations',
    sa.Column('encounter_id', sa.String(length=26), nullable=False),
    sa.Column('patient_id', sa.String(length=26), nullable=False),
    sa.Column('code_system', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('display', sa.String(length=200), nullable=True),
    sa.Column('value_quantity', sa.Float(), nullable=True),
    sa.Column('value_unit', sa.String(length=40), nullable=True),
    sa.Column('value_string', sa.String(length=400), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_observations_encounter_id_encounters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations'))
    )
    op.create_index(op.f('ix_observations_code'), 'observations', ['code'], unique=False)
    op.create_index(op.f('ix_observations_effective_at'), 'observations', ['effective_at'], unique=False)
    op.create_index(op.f('ix_observations_encounter_id'), 'observations', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_observations_patient_id'), 'observations', ['patient_id'], unique=False)
    op.create_table('stock_events',
    sa.Column('batch_id', sa.String(length=26), nullable=True),
    sa.Column('supply_item_id', sa.String(length=26), nullable=False),
    sa.Column('facility_id', sa.String(length=26), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference_id', sa.String(length=80), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('extra', app.db.base.JSONBOrJSON(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], name=op.f('fk_stock_events_batch_id_stock_batches'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_events'))
    )
    op.create_index(op.f('ix_stock_events_batch_id'), 'stock_events', ['batch_id'], unique=False)
    op.create_index(op.f('ix_stock_events_event_hash'), 'stock_events', ['event_hash'], unique=False)
    op.create_index(op.f('ix_stock_events_event_type'), 'stock_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_stock_events_facility_id'), 'stock_events', ['facility_id'], unique=False)
    op.create_index(op.f('ix_stock_events_occurred_at'), 'stock_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_stock_events_supply_item_id'), 'stock_events', ['supply_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_events_supply_item_id'), table_name='stock_events')
    op.drop_index(op.f('ix_stock_events_occurred_at'), table_name='stock_events')
    op.drop_index(op.f('ix_stock_events_facility_id'), table_name='stock_events')
    op.drop_index(op.f('ix_stock_events_event_type'), table_name='stock_events')
    op.drop_index(op.f('ix_stock_events_event_hash'), table_name='stock_events')
    op.drop_index(op.f('ix_stock_events_batch_id'), table_name='stock_events')
    op.drop_table('stock_events')
    op.drop_index(op.f('ix_observations_patient_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_encounter_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_effective_at'), table_name='observations')
    op.drop_index(op.f('ix_observations_code'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_facility_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('stock_transfers')
    op.drop_index(op.f('ix_stock_batches_supply_item_id'), table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_lot_number'), table_name='stock_batches')
    op.drop_index('ix_stock_batches_facility_item', table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_facility_id'), table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_expires_on'), table_name='stock_batches')
    op.drop_table('stock_batches')
    op.drop_index(op.f('ix_encounters_started_at'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_facility_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_consents_scope'), table_name='consents')
    op.drop_index(op.f('ix_consents_patient_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_supply_items_name'), table_name='supply_items')
    op.drop_index(op.f('ix_supply_items_code'), table_name='supply_items')
    op.drop_index(op.f('ix_supply_items_category'), table_name='supply_items')
    op.drop_table('supply_items')
    op.drop_index(op.f('ix_patients_nin'), table_name='patients')
    op.drop_index('ix_patients_family_name_trgm', table_name='patients', postgresql_using='gin', postgresql_ops={'family_name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_patients_district'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_facilities_name'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_level'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_district'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_code'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_audit_log_resource_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_resource_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_resource', table_name='audit_log')
    op.drop_index('ix_audit_log_actor_time', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_role'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_facility_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
