"""caregiver_links_table

Revision ID: c07e02b0024b
Revises: 498638f987ec
Create Date: 2026-05-26 22:11:40.062351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07e02b0024b'
down_revision: Union[str, Sequence[str], None] = '498638f987ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver_links',
    sa.Column('caregiver_id', sa.String(length=26), nullable=False),
    sa.Column('child_id', sa.String(length=26), nullable=False),
    sa.Column('relationship', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['patients.id'], name=op.f('fk_caregiver_links_caregiver_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['child_id'], ['patients.id'], name=op.f('fk_caregiver_links_child_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_caregiver_links')),
    sa.UniqueConstraint('caregiver_id', 'child_id', name='uq_caregiver_links_pair')
    )
    op.create_index('ix_caregiver_links_caregiver_child', 'caregiver_links', ['caregiver_id', 'child_id'], unique=False)
    op.create_index(op.f('ix_caregiver_links_caregiver_id'), 'caregiver_links', ['caregiver_id'], unique=False)
    op.create_index(op.f('ix_caregiver_links_child_id'), 'caregiver_links', ['child_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_caregiver_links_child_id'), table_name='caregiver_links')
    op.drop_index(op.f('ix_caregiver_links_caregiver_id'), table_name='caregiver_links')
    op.drop_index('ix_caregiver_links_caregiver_child', table_name='caregiver_links')
    op.drop_table('caregiver_links')
    # ### end Alembic commands ###
