"""Realistic Uganda demo data — facilities, patients, encounters, supply chain.

Districts, facility levels, and drug codes follow the Uganda MoH conventions.
This is *prototype demo data*, not production reference data.
"""

from __future__ import annotations

from datetime import date

# ── Facilities (real-world references; coordinates approximate) ──────────────
FACILITIES: list[dict] = [
    {
        "code": "MUL-NRH-001",
        "name": "Mulago National Referral Hospital",
        "level": "NRH",
        "district": "Kampala",
        "sub_county": "Kawempe",
        "latitude": 0.3476,
        "longitude": 32.5825,
    },
    {
        "code": "GUL-RRH-002",
        "name": "Gulu Regional Referral Hospital",
        "level": "RRH",
        "district": "Gulu",
        "sub_county": "Bardege",
        "latitude": 2.7747,
        "longitude": 32.2990,
    },
    {
        "code": "MBR-RRH-003",
        "name": "Mbarara Regional Referral Hospital",
        "level": "RRH",
        "district": "Mbarara",
        "sub_county": "Kakoba",
        "latitude": -0.6062,
        "longitude": 30.6586,
    },
    {
        "code": "MBL-RRH-004",
        "name": "Mbale Regional Referral Hospital",
        "level": "RRH",
        "district": "Mbale",
        "sub_county": "Industrial",
        "latitude": 1.0826,
        "longitude": 34.1758,
    },
    {
        "code": "ARU-RRH-005",
        "name": "Arua Regional Referral Hospital",
        "level": "RRH",
        "district": "Arua",
        "sub_county": "Arua Hill",
        "latitude": 3.0193,
        "longitude": 30.9111,
    },
    {
        "code": "KMP-HC4-101",
        "name": "Kisenyi HC IV",
        "level": "HC IV",
        "district": "Kampala",
        "sub_county": "Central",
        "latitude": 0.3120,
        "longitude": 32.5732,
    },
    {
        "code": "GUL-HC3-201",
        "name": "Lacor HC III (annex)",
        "level": "HC III",
        "district": "Gulu",
        "sub_county": "Pece",
        "latitude": 2.7693,
        "longitude": 32.2880,
    },
]


# ── Supply items (Uganda EMHSLU codes) ───────────────────────────────────────
SUPPLY_ITEMS: list[dict] = [
    {
        "code": "ACT-AL-001",
        "name": "Artemether/Lumefantrine 20/120 mg tablet",
        "category": "medicine",
        "unit": "tablet",
        "reorder_threshold": 500,
        "requires_cold_chain": False,
    },
    {
        "code": "ORS-001",
        "name": "Oral Rehydration Salts sachet",
        "category": "medicine",
        "unit": "sachet",
        "reorder_threshold": 300,
        "requires_cold_chain": False,
    },
    {
        "code": "RUTF-001",
        "name": "Ready-to-Use Therapeutic Food 92g sachet",
        "category": "medicine",
        "unit": "sachet",
        "reorder_threshold": 200,
        "requires_cold_chain": False,
    },
    {
        "code": "VAC-BCG-001",
        "name": "BCG vaccine 20-dose vial",
        "category": "vaccine",
        "unit": "vial",
        "reorder_threshold": 40,
        "requires_cold_chain": True,
    },
    {
        "code": "VAC-OPV-001",
        "name": "Oral Polio Vaccine 20-dose vial",
        "category": "vaccine",
        "unit": "vial",
        "reorder_threshold": 50,
        "requires_cold_chain": True,
    },
    {
        "code": "VAC-MR-001",
        "name": "Measles-Rubella vaccine 10-dose vial",
        "category": "vaccine",
        "unit": "vial",
        "reorder_threshold": 60,
        "requires_cold_chain": True,
    },
    {
        "code": "CON-GLOVE-001",
        "name": "Examination glove (pair)",
        "category": "consumable",
        "unit": "pair",
        "reorder_threshold": 1000,
        "requires_cold_chain": False,
    },
]


# ── Synthetic patients (names anonymised; NINs follow NIRA format) ───────────
PATIENTS: list[dict] = [
    {
        "nin": "CM85051712345X",
        "given_name": "Achieng",
        "family_name": "Akello",
        "gender": "female",
        "birth_date": date(1985, 5, 17),
        "phone": "+256772111222",
        "email": None,
        "district": "Gulu",
        "sub_county": "Pece",
        "parish": "Pawel",
        "village": "Kanyagoga",
    },
    {
        "nin": "CM91021867890X",
        "given_name": "Okello",
        "family_name": "Otim",
        "gender": "male",
        "birth_date": date(1991, 2, 18),
        "phone": "+256701222333",
        "district": "Gulu",
        "sub_county": "Bardege",
        "parish": "Pageya",
        "village": "Cwero",
    },
    {
        "nin": "CF88110755001A",
        "given_name": "Nakato",
        "family_name": "Namuyanja",
        "gender": "female",
        "birth_date": date(1988, 11, 7),
        "phone": "+256779333444",
        "district": "Kampala",
        "sub_county": "Central",
        "parish": "Nakasero",
        "village": "Plot 7 Kampala Rd",
    },
    {
        "nin": "CM92030515999B",
        "given_name": "Tumusiime",
        "family_name": "Asiimwe",
        "gender": "male",
        "birth_date": date(1992, 3, 5),
        "phone": "+256703444555",
        "district": "Mbarara",
        "sub_county": "Kakoba",
        "parish": "Kakoba",
        "village": "Booma",
    },
    {
        "nin": "CF95061277321C",
        "given_name": "Nabirye",
        "family_name": "Naigaga",
        "gender": "female",
        "birth_date": date(1995, 6, 12),
        "phone": "+256772555666",
        "district": "Mbale",
        "sub_county": "Industrial",
        "parish": "Namatala",
        "village": "Bumboi",
    },
    {
        "nin": "CM83091998765D",
        "given_name": "Andama",
        "family_name": "Drici",
        "gender": "male",
        "birth_date": date(1983, 9, 19),
        "phone": "+256701666777",
        "district": "Arua",
        "sub_county": "Arua Hill",
        "parish": "Tanganyika",
        "village": "Ediofe",
    },
    {
        "nin": "CF99041088123E",
        "given_name": "Atim",
        "family_name": "Lawino",
        "gender": "female",
        "birth_date": date(1999, 4, 10),
        "phone": "+256778777888",
        "district": "Gulu",
        "sub_county": "Bardege",
        "parish": "Kasubi",
        "village": "Layibi",
    },
    {
        "nin": "CM87122144556F",
        "given_name": "Muwanga",
        "family_name": "Sserwadda",
        "gender": "male",
        "birth_date": date(1987, 12, 21),
        "phone": "+256776888999",
        "district": "Kampala",
        "sub_county": "Makindye",
        "parish": "Kibuye",
        "village": "Plot 14",
    },
    {
        "nin": "CF02071633998G",
        "given_name": "Aceng",
        "family_name": "Oryem",
        "gender": "female",
        "birth_date": date(2002, 7, 16),
        "phone": "+256776999000",
        "district": "Lira",
        "sub_county": "Lira Central",
        "parish": "Adyel",
        "village": "Aboke",
    },
    {
        "nin": "CM05081222110H",
        "given_name": "Kato",
        "family_name": "Mukasa",
        "gender": "male",
        "birth_date": date(2005, 8, 12),
        "phone": None,
        "district": "Wakiso",
        "sub_county": "Entebbe",
        "parish": "Kitooro",
        "village": "Bugonga",
    },
    {
        "nin": "CF18051144556J",
        "given_name": "Nansubuga",
        "family_name": "Kayemba",
        "gender": "female",
        "birth_date": date(2018, 5, 11),
        "phone": None,
        "district": "Kampala",
        "sub_county": "Kawempe",
        "parish": "Bwaise",
        "village": "Plot 9",
    },
]


# ── Demo users (staff) ───────────────────────────────────────────────────────
USERS: list[dict] = [
    {
        "username": "admin",
        "full_name": "Demo Administrator",
        "role": "ministry_admin",
        "password": "admin1234",
        "facility_code": None,
    },
    {
        "username": "nurse.gulu",
        "full_name": "Susan Akwero",
        "role": "worker",
        "password": "demo1234",
        "facility_code": "GUL-RRH-002",
    },
    {
        "username": "doctor.kampala",
        "full_name": "James Lubega",
        "role": "worker",
        "password": "demo1234",
        "facility_code": "MUL-NRH-001",
    },
    {
        "username": "pharmacist.mbarara",
        "full_name": "Grace Tumushabe",
        "role": "pharmacist",
        "password": "demo1234",
        "facility_code": "MBR-RRH-003",
    },
    {
        "username": "dho.gulu",
        "full_name": "Robert Komakech",
        "role": "district_admin",
        "password": "demo1234",
        "facility_code": "GUL-RRH-002",
    },
]


VACCINE_CODES = {
    "BCG": ("http://snomed.info/sct", "42284007", "BCG vaccine product"),
    "OPV": ("http://snomed.info/sct", "836382009", "Oral polio vaccine product"),
    "MR":  ("http://snomed.info/sct", "836383004", "Measles-Rubella vaccine product"),
}
