"""Realistic Uganda demo data — facilities, patients, encounters, supply chain.

Districts, facility levels, and drug codes follow the Uganda MoH conventions.
This is *prototype demo data*, not production reference data.
"""

from __future__ import annotations

from datetime import date

# ── Facilities (real-world references; coordinates approximate) ──────────────
FACILITIES: list[dict] = [
    {
        "code": "MUL-NRH-001",
        "name": "Mulago National Referral Hospital",
        "level": "NRH",
        "district": "Kampala",
        "sub_county": "Kawempe",
        "latitude": 0.3476,
        "longitude": 32.5825,
    },
    {
        "code": "GUL-RRH-002",
        "name": "Gulu Regional Referral Hospital",
        "level": "RRH",
        "district": "Gulu",
        "sub_county": "Bardege",
        "latitude": 2.7747,
        "longitude": 32.2990,
    },
    {
        "code": "MBR-RRH-003",
        "name": "Mbarara Regional Referral Hospital",
        "level": "RRH",
        "district": "Mbarara",
        "sub_county": "Kakoba",
        "latitude": -0.6062,
        "longitude": 30.6586,
    },
    {
        "code": "MBL-RRH-004",
        "name": "Mbale Regional Referral Hospital",
        "level": "RRH",
        "district": "Mbale",
        "sub_county": "Industrial",
        "latitude": 1.0826,
        "longitude": 34.1758,
    },
    {
        "code": "ARU-RRH-005",
        "name": "Arua Regional Referral Hospital",
        "level": "RRH",
        "district": "Arua",
        "sub_county": "Arua Hill",
        "latitude": 3.0193,
        "longitude": 30.9111,
    },
    {
        "code": "KMP-HC4-101",
        "name": "Kisenyi HC IV",
        "level": "HC IV",
        "district": "Kampala",
        "sub_county": "Central",
        "latitude": 0.3120,
        "longitude": 32.5732,
    },
    {
        "code": "GUL-HC3-201",
        "name": "Lacor HC III (annex)",
        "level": "HC III",
        "district": "Gulu",
        "sub_county": "Pece",
        "latitude": 2.7693,
        "longitude": 32.2880,
    },
    {
        "code": "WAK-HC4-301",
        "name": "Entebbe Grade B Hospital",
        "level": "HC IV",
        "district": "Wakiso",
        "sub_county": "Entebbe",
        "latitude": 0.0626,
        "longitude": 32.4630,
    },
    {
        "code": "LIR-HC4-401",
        "name": "Lira Central HC IV",
        "level": "HC IV",
        "district": "Lira",
        "sub_county": "Lira Central",
        "latitude": 2.2350,
        "longitude": 32.9020,
    },
    {
        "code": "JIN-RRH-501",
        "name": "Jinja Regional Referral Hospital",
        "level": "RRH",
        "district": "Jinja",
        "sub_county": "Jinja Central",
        "latitude": 0.4250,
        "longitude": 33.2030,
    },
    {
        "code": "MBR-HC3-301",
        "name": "Kakoba HC III",
        "level": "HC III",
        "district": "Mbarara",
        "sub_county": "Kakoba",
        "latitude": -0.6210,
        "longitude": 30.6451,
    },
    {
        "code": "MBL-HC3-401",
        "name": "Namatala HC III",
        "level": "HC III",
        "district": "Mbale",
        "sub_county": "Namatala",
        "latitude": 1.0789,
        "longitude": 34.1822,
    },
    {
        "code": "ARU-HC3-501",
        "name": "Arua Hill HC III",
        "level": "HC III",
        "district": "Arua",
        "sub_county": "Arua Hill",
        "latitude": 3.0241,
        "longitude": 30.9088,
    },
    {
        "code": "KMP-HC2-102",
        "name": "Nakulabye HC II",
        "level": "HC II",
        "district": "Kampala",
        "sub_county": "Rubaga",
        "latitude": 0.3308,
        "longitude": 32.5443,
    },
]


# ── Supply items (Uganda EMHSLU codes) ───────────────────────────────────────
SUPPLY_ITEMS: list[dict] = [
    {
        "code": "ACT-AL-001",
        "name": "Artemether/Lumefantrine 20/120 mg tablet",
        "category": "medicine",
        "unit": "tablet",
        "reorder_threshold": 500,
        "requires_cold_chain": False,
    },
    {
        "code": "ORS-001",
        "name": "Oral Rehydration Salts sachet",
        "category": "medicine",
        "unit": "sachet",
        "reorder_threshold": 300,
        "requires_cold_chain": False,
    },
    {
        "code": "RUTF-001",
        "name": "Ready-to-Use Therapeutic Food 92g sachet",
        "category": "medicine",
        "unit": "sachet",
        "reorder_threshold": 200,
        "requires_cold_chain": False,
    },
    {
        "code": "VAC-BCG-001",
        "name": "BCG vaccine 20-dose vial",
        "category": "vaccine",
        "unit": "vial",
        "reorder_threshold": 40,
        "requires_cold_chain": True,
    },
    {
        "code": "VAC-OPV-001",
        "name": "Oral Polio Vaccine 20-dose vial",
        "category": "vaccine",
        "unit": "vial",
        "reorder_threshold": 50,
        "requires_cold_chain": True,
    },
    {
        "code": "VAC-MR-001",
        "name": "Measles-Rubella vaccine 10-dose vial",
        "category": "vaccine",
        "unit": "vial",
        "reorder_threshold": 60,
        "requires_cold_chain": True,
    },
    {
        "code": "CON-GLOVE-001",
        "name": "Examination glove (pair)",
        "category": "consumable",
        "unit": "pair",
        "reorder_threshold": 1000,
        "requires_cold_chain": False,
    },
    {
        "code": "VAC-DPT-001",
        "name": "DPT-HepB-Hib (pentavalent) 10-dose vial",
        "category": "vaccine",
        "unit": "vial",
        "reorder_threshold": 80,
        "requires_cold_chain": True,
    },
    {
        "code": "VAC-PCV-001",
        "name": "Pneumococcal Conjugate Vaccine 4-dose vial",
        "category": "vaccine",
        "unit": "vial",
        "reorder_threshold": 60,
        "requires_cold_chain": True,
    },
    {
        "code": "VAC-YF-001",
        "name": "Yellow Fever vaccine 5-dose vial",
        "category": "vaccine",
        "unit": "vial",
        "reorder_threshold": 30,
        "requires_cold_chain": True,
    },
    {
        "code": "MED-PARA-001",
        "name": "Paracetamol 500 mg tablet",
        "category": "medicine",
        "unit": "tablet",
        "reorder_threshold": 2000,
        "requires_cold_chain": False,
    },
    {
        "code": "MED-AMOX-001",
        "name": "Amoxicillin 250 mg capsule",
        "category": "medicine",
        "unit": "capsule",
        "reorder_threshold": 1000,
        "requires_cold_chain": False,
    },
    {
        "code": "CON-SYR-001",
        "name": "Syringe 5 ml with needle",
        "category": "consumable",
        "unit": "syringe",
        "reorder_threshold": 800,
        "requires_cold_chain": False,
    },
    {
        "code": "DIA-MRDT-001",
        "name": "Malaria Rapid Diagnostic Test kit",
        "category": "consumable",
        "unit": "kit",
        "reorder_threshold": 300,
        "requires_cold_chain": False,
    },
]


# ── Synthetic patients (names anonymised; NINs follow NIRA format) ───────────
PATIENTS: list[dict] = [
    {
        "nin": "CM85051712345X",
        "given_name": "Achieng",
        "family_name": "Akello",
        "gender": "female",
        "birth_date": date(1985, 5, 17),
        "phone": "+256772111222",
        "email": None,
        "district": "Gulu",
        "sub_county": "Pece",
        "parish": "Pawel",
        "village": "Kanyagoga",
    },
    {
        "nin": "CM91021867890X",
        "given_name": "Okello",
        "family_name": "Otim",
        "gender": "male",
        "birth_date": date(1991, 2, 18),
        "phone": "+256701222333",
        "district": "Gulu",
        "sub_county": "Bardege",
        "parish": "Pageya",
        "village": "Cwero",
    },
    {
        "nin": "CF88110755001A",
        "given_name": "Nakato",
        "family_name": "Namuyanja",
        "gender": "female",
        "birth_date": date(1988, 11, 7),
        "phone": "+256779333444",
        "district": "Kampala",
        "sub_county": "Central",
        "parish": "Nakasero",
        "village": "Plot 7 Kampala Rd",
    },
    {
        "nin": "CM92030515999B",
        "given_name": "Tumusiime",
        "family_name": "Asiimwe",
        "gender": "male",
        "birth_date": date(1992, 3, 5),
        "phone": "+256703444555",
        "district": "Mbarara",
        "sub_county": "Kakoba",
        "parish": "Kakoba",
        "village": "Booma",
    },
    {
        "nin": "CF95061277321C",
        "given_name": "Nabirye",
        "family_name": "Naigaga",
        "gender": "female",
        "birth_date": date(1995, 6, 12),
        "phone": "+256772555666",
        "district": "Mbale",
        "sub_county": "Industrial",
        "parish": "Namatala",
        "village": "Bumboi",
    },
    {
        "nin": "CM83091998765D",
        "given_name": "Andama",
        "family_name": "Drici",
        "gender": "male",
        "birth_date": date(1983, 9, 19),
        "phone": "+256701666777",
        "district": "Arua",
        "sub_county": "Arua Hill",
        "parish": "Tanganyika",
        "village": "Ediofe",
    },
    {
        "nin": "CF99041088123E",
        "given_name": "Atim",
        "family_name": "Lawino",
        "gender": "female",
        "birth_date": date(1999, 4, 10),
        "phone": "+256778777888",
        "district": "Gulu",
        "sub_county": "Bardege",
        "parish": "Kasubi",
        "village": "Layibi",
    },
    {
        "nin": "CM87122144556F",
        "given_name": "Muwanga",
        "family_name": "Sserwadda",
        "gender": "male",
        "birth_date": date(1987, 12, 21),
        "phone": "+256776888999",
        "district": "Kampala",
        "sub_county": "Makindye",
        "parish": "Kibuye",
        "village": "Plot 14",
    },
    {
        "nin": "CF02071633998G",
        "given_name": "Aceng",
        "family_name": "Oryem",
        "gender": "female",
        "birth_date": date(2002, 7, 16),
        "phone": "+256776999000",
        "district": "Lira",
        "sub_county": "Lira Central",
        "parish": "Adyel",
        "village": "Aboke",
    },
    {
        "nin": "CM05081222110H",
        "given_name": "Kato",
        "family_name": "Mukasa",
        "gender": "male",
        "birth_date": date(2005, 8, 12),
        "phone": None,
        "district": "Wakiso",
        "sub_county": "Entebbe",
        "parish": "Kitooro",
        "village": "Bugonga",
    },
    {
        "nin": "CF18051144556J",
        "given_name": "Nansubuga",
        "family_name": "Kayemba",
        "gender": "female",
        "birth_date": date(2018, 5, 11),
        "phone": None,
        "district": "Kampala",
        "sub_county": "Kawempe",
        "parish": "Bwaise",
        "village": "Plot 9",
    },
    # ── Pregnant / ANC cohort (for analytics narrative) ──
    {
        "nin": "CF93081244778K",
        "given_name": "Namaganda",
        "family_name": "Nakitende",
        "gender": "female",
        "birth_date": date(1993, 8, 12),
        "phone": "+256775111223",
        "district": "Wakiso",
        "sub_county": "Entebbe",
        "parish": "Kitooro",
        "village": "Bugonga",
    },
    {
        "nin": "CF96112266889L",
        "given_name": "Auma",
        "family_name": "Akello",
        "gender": "female",
        "birth_date": date(1996, 11, 22),
        "phone": "+256775222334",
        "district": "Gulu",
        "sub_county": "Bardege",
        "parish": "Layibi",
        "village": "Lukome",
    },
    {
        "nin": "CF94060533445M",
        "given_name": "Akiteng",
        "family_name": "Atim",
        "gender": "female",
        "birth_date": date(1994, 6, 5),
        "phone": "+256775333445",
        "district": "Lira",
        "sub_county": "Lira Central",
        "parish": "Adyel",
        "village": "Ayami",
    },
    # ── Paediatric cohort (immunisation analytics) ──
    {
        "nin": "CM21030877665N",
        "given_name": "Wasswa",
        "family_name": "Kalule",
        "gender": "male",
        "birth_date": date(2021, 3, 8),
        "phone": None,
        "district": "Kampala",
        "sub_county": "Makindye",
        "parish": "Kibuye",
        "village": "Plot 23",
    },
    {
        "nin": "CF22050466554P",
        "given_name": "Babirye",
        "family_name": "Nakimuli",
        "gender": "female",
        "birth_date": date(2022, 5, 4),
        "phone": None,
        "district": "Jinja",
        "sub_county": "Jinja Central",
        "parish": "Bugembe",
        "village": "Plot 8",
    },
    {
        "nin": "CM23071955443Q",
        "given_name": "Kintu",
        "family_name": "Ssempa",
        "gender": "male",
        "birth_date": date(2023, 7, 19),
        "phone": None,
        "district": "Wakiso",
        "sub_county": "Entebbe",
        "parish": "Katabi",
        "village": "Kigungu",
    },
    {
        "nin": "CF24091344332R",
        "given_name": "Apio",
        "family_name": "Lakot",
        "gender": "female",
        "birth_date": date(2024, 9, 13),
        "phone": None,
        "district": "Gulu",
        "sub_county": "Pece",
        "parish": "Kasubi",
        "village": "Lacor",
    },
    # ── Elderly / chronic-disease cohort ──
    {
        "nin": "CM55041233221T",
        "given_name": "Mugisha",
        "family_name": "Kirunda",
        "gender": "male",
        "birth_date": date(1955, 4, 12),
        "phone": "+256775444556",
        "district": "Mbarara",
        "sub_county": "Kakoba",
        "parish": "Booma",
        "village": "Plot 56",
    },
    {
        "nin": "CF58081822110U",
        "given_name": "Nyangoma",
        "family_name": "Kabazzi",
        "gender": "female",
        "birth_date": date(1958, 8, 18),
        "phone": "+256775555667",
        "district": "Mbale",
        "sub_county": "Industrial",
        "parish": "Bumboi",
        "village": "Plot 32",
    },
    {
        "nin": "CM60111511009V",
        "given_name": "Onyango",
        "family_name": "Otim",
        "gender": "male",
        "birth_date": date(1960, 11, 15),
        "phone": "+256775666778",
        "district": "Lira",
        "sub_county": "Lira Central",
        "parish": "Aboke",
        "village": "Akia",
    },
    {
        "nin": "CF65021400998W",
        "given_name": "Asio",
        "family_name": "Adongo",
        "gender": "female",
        "birth_date": date(1965, 2, 14),
        "phone": "+256775777889",
        "district": "Arua",
        "sub_county": "Arua Hill",
        "parish": "Ediofe",
        "village": "Plot 19",
    },
    # ── Working-age adults across districts ──
    {
        "nin": "CM78100766775Y",
        "given_name": "Owino",
        "family_name": "Opio",
        "gender": "male",
        "birth_date": date(1978, 10, 7),
        "phone": "+256775888990",
        "district": "Jinja",
        "sub_county": "Jinja Central",
        "parish": "Walukuba",
        "village": "Plot 14",
    },
    {
        "nin": "CF82051555664Z",
        "given_name": "Tushabe",
        "family_name": "Mukamutara",
        "gender": "female",
        "birth_date": date(1982, 5, 15),
        "phone": "+256775999001",
        "district": "Mbarara",
        "sub_county": "Kakoba",
        "parish": "Kakoba",
        "village": "Plot 71",
    },
    {
        "nin": "CM89071244553X",
        "given_name": "Byaruhanga",
        "family_name": "Sserwanga",
        "gender": "male",
        "birth_date": date(1989, 7, 12),
        "phone": "+256776000112",
        "district": "Wakiso",
        "sub_county": "Entebbe",
        "parish": "Kitooro",
        "village": "Bugonga",
    },
    {
        "nin": "CF90030933442Y",
        "given_name": "Nabasa",
        "family_name": "Kemigisha",
        "gender": "female",
        "birth_date": date(1990, 3, 9),
        "phone": "+256776111223",
        "district": "Mbale",
        "sub_county": "Industrial",
        "parish": "Namatala",
        "village": "Plot 8",
    },
]


# ── Demo users (staff) ───────────────────────────────────────────────────────
USERS: list[dict] = [
    {
        "username": "admin",
        "full_name": "Demo Administrator",
        "role": "ministry_admin",
        "password": "admin1234",
        "facility_code": None,
    },
    {
        "username": "nurse.gulu",
        "full_name": "Susan Akwero",
        "role": "worker",
        "password": "demo1234",
        "facility_code": "GUL-RRH-002",
    },
    {
        "username": "doctor.kampala",
        "full_name": "James Lubega",
        "role": "worker",
        "password": "demo1234",
        "facility_code": "MUL-NRH-001",
    },
    {
        "username": "pharmacist.mbarara",
        "full_name": "Grace Tumushabe",
        "role": "pharmacist",
        "password": "demo1234",
        "facility_code": "MBR-RRH-003",
    },
    {
        "username": "dho.gulu",
        "full_name": "Robert Komakech",
        "role": "district_admin",
        "password": "demo1234",
        "facility_code": "GUL-RRH-002",
    },
]


VACCINE_CODES = {
    "BCG": ("http://snomed.info/sct", "42284007", "BCG vaccine product"),
    "OPV": ("http://snomed.info/sct", "836382009", "Oral polio vaccine product"),
    "MR":  ("http://snomed.info/sct", "836383004", "Measles-Rubella vaccine product"),
    "DPT": (
        "http://snomed.info/sct",
        "428601000124108",
        "DPT-HepB-Hib (pentavalent) vaccine product",
    ),
    "PCV": ("http://snomed.info/sct", "836389000", "Pneumococcal conjugate vaccine product"),
    "YF":  ("http://snomed.info/sct", "836385006", "Yellow fever vaccine product"),
}


# ── Encounter reasons by patient persona ─────────────────────────────────────
# Used by the richer-encounters generator to bias each patient's history
# toward a believable clinical profile (ANC, paediatric immunisation,
# chronic disease, general OPD).

ANC_REASONS = [
    "Antenatal visit — 1st trimester",
    "Antenatal visit — 2nd trimester",
    "Antenatal visit — 3rd trimester",
    "ANC follow-up + iron supplementation",
    "Postnatal review",
]

PAEDIATRIC_REASONS = [
    "Routine immunisation visit",
    "Growth monitoring",
    "Acute febrile illness (suspect malaria)",
    "Cough and cold review",
    "Diarrhoea + dehydration (mild)",
]

CHRONIC_REASONS = [
    "Hypertension follow-up",
    "Type 2 diabetes follow-up",
    "Asthma review",
    "Arthritis pain management",
    "Routine chronic-disease check",
]

GENERAL_REASONS = [
    "Outpatient consultation",
    "Fever and chills",
    "Headache and fatigue",
    "Routine check-up",
    "Sexually transmitted infection screen",
]

# ICD-10 diagnosis pool, biased by persona type
DIAGNOSIS_BY_PERSONA = {
    "anc":        ["O09.5", "O09.3", "Z34.0", "Z34.9"],
    "paediatric": ["B54", "A09.9", "J06.9", "Z23"],
    "chronic":    ["I10", "E11.9", "J45.9", "M19.9"],
    "general":    ["B54", "A09.9", "J06.9", "R51", "Z00.0"],
}
